services:
  aria2:
    image: ${DOCKER_REGISTRY}/aria2:latest
    hostname: aria2
    container_name: aria2
    environment:
      - TZ=Asia/Shanghai
      - USER=${DEFAULT_USER}
      - UID=${UID}
      - RPC_SECRET=dockenv
      - ARIA2_PORT=6800
      - WEBUI_PORT=6801
      - DHT_PORT="6802-6999"
    ports:
      - "6800:6800"
      - "6801:6801"
      - "6802-6999:6802-6999"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $HOME/Downloads:/data/downloads
      - ../conf/aria2c:/etc/aria2c
      - ../logs/aria2c:/data.logs
    networks:
      default:

networks:
  default:
    name: dockenv
    external: true
