services:
  dragonflydb:
    image: ${DOCKER_REGISTRY}/dragonflydb:latest
    hostname: dragonflydb
    container_name: dragonflydb
    restart: always
    ulimits:
      memlock: -1
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "${DRAGONFLYDB_PORT}:6379"
    volumes:
      - dragonflydb:/data
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    networks:
      dockenv_dockenv:
        ipv4_address: ${IP_DRAGONFLYDB}

networks:
  dockenv_dockenv:
    external: true
