services:
  elastic:
    image: ${DOCKER_REGISTRY}/elastic:latest
    hostname: elastic
    container_name: elastic
    restart: always
    expose:
      - 9300
      - 9200
    environment:
      - ELASTIC_PASSWORD=${DEFAULT_PASSWD}
      # 此配置会导致无法启动
      # - ENROLLMENT_TOKEN=dockenv
      - cluster.name=${NAME}
      - discovery.type=single-node
      # 默认禁用 elasticsearch https 和登陆账号密码 仅适用于 Docker 测试环境
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - script.painless.regex.enabled=true
      # - node.master=false
      # - node.data=true
      - TZ=${TIMEZONE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      # - elastic:/usr/share/elasticsearch/data
      - ../data/elastic:/data
      - ../logs/elastic:/usr/share/elasticsearch/logs
      # - ${ELASTICSEARCH_CONF_FILE}:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "${ELASTIC_WEB_PORT}:9200"
      - "${ELASTIC_PORT}:9300"
    networks:
      default:
        ipv4_address: ${IP_ELASTICSEARCH}

  # volumes /usr/share/logstash/config/
  logstash:
    image: ${DOCKER_REGISTRY}/logstash:latest
    hostname: logstash
    container_name: logstash
    restart: always
    command: logstash -f ./conf/logstash-filebeat.conf
    expose:
      - 5044
    # volumes:
    # 映射到容器中
    # - ./logstash/conf/logstash-filebeat.conf:/usr/share/logstash/conf/logstash-filebeat.conf
    # - ./logstash/conf/logstash.yml:/usr/share/logstash/config/logstash.yml
    environment:
      - TZ=${TIMEZONE}
      - ELASTICSEARCH_HOSTS=["http://elastic:9200"]
      # 解决logstash监控连接报错
      - xpack.monitoring.elasticsearch.hosts=http://elastic:9200
    ports:
      - "${LOGSTASH_WEB_PORT}:9600"
      - "${LOGSTASH_PORT}:5044"
    depends_on:
      - elastic
    links:
      - elastic:elasticsearch
    networks:
      default:
        ipv4_address: ${IP_LOGSTASH}

  kibana:
    image: ${DOCKER_REGISTRY}/kibana:latest
    hostname: kibana
    container_name: kibana
    restart: always
    expose:
      - 5601
    environment:
      - TZ=${TIMEZONE}
      - SERVER_NAME=kibana
      # - ELASTICSEARCH_HOSTS=["http://${ELASTICSEARCH_IP}:9200"]
      - ELASTICSEARCH_HOSTS=["http://elastic:9200"]
      - LS_JAVA_OPTS=-Xmx512m -Xms512m
    # volumes:
    # - ../conf/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on:
      - elastic
    links:
      - elastic:elastic
    networks:
      default:
        ipv4_address: ${IP_KIBANA}

networks:
  default:
    name: dockenv
    external: true
