services:
  # default password ,default user: root
  # grep 'Password:' /etc/gitlab/initial_root_password
  gitlab:
    image: registry.gitlab.cn/omnibus/gitlab-jh:latest
    hostname: gitlab
    container_name: gitlab
    restart: always
    shm_size: 512mb
    environment:
      - GITLAB_ROOT_PASSWORD=${GITLAB_PASSWORD}
    ports:
      - '2022:22'
      - '2080:80'
      - '2443:443'
    volumes:
      # - gitlabconf:/etc/gitlab
      # - gitlablogs:/var/log/gitlab
      # - gitlabdata:/var/opt/gitlab
      - ../conf/gitlab:/etc/gitlab
      - ../logs/gitlab:/var/log/gitlab
      - ../data/gitlab:/var/opt/gitlab
    networks:
      dockenv:

networks:
  dockenv_dockenv:
    external: true
