services:
  portainer:
    image: portainer/portainer-ee:latest
    hostname: portainer
    container_name: portainer
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../data/portainer:/data
    networks:
      lnmp_dockenv:
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

networks:
  lnmp_dockenv:
    external: true
