services:
  mariadb:
    image: ${DOCKER_REGISTRY}/mariadb:latest
    hostname: mariadb
    container_name: mariadb
    restart: always
    expose:
      - '3306'
    ports:
      - '${MARIADB_PORT}:3306'
    volumes:
      - ../data/mariadb:/var/lib/mysql
      - ../logs/mariadb/:/var/log/mysql
    environment:
      - TZ=${TIMEZONE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    #only for container without host
    networks:
      dockenv_dockenv:
        ipv4_address: ${IP_MARIADB}

networks:
  dockenv_dockenv:
    external: true
