services:
  # Object Storage Service(Compatible With Amazon S3 Protocol)
  minio:
    image: ${DOCKER_REGISTRY}/minio:latest
    hostname: minio
    container_name: minio
    restart: always
    expose:
      - 19000
      - 1921
    environment:
      - MINIO_ADDRESS=0.0.0.0:${MINIO_PORT} # minio port
      - MINIO_CONSOLE_ADDRESS=0.0.0.0:${MINIO_WEB_PORT} # minio console port
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    command: server /data --ftp="address=:${MINIO_FTP_PORT}" --ftp="passive-port-range=30000-40000"
    # Add Sftp Support
    # --sftp="address=:8022" --sftp="ssh-private-key=${HOME}/.ssh/id_rsa"
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
      - ${MINIO_WEB_PORT}:${MINIO_WEB_PORT}
      - ${MINIO_FTP_PORT}:${MINIO_FTP_PORT}
    volumes:
      - ../data/minio:/data
    networks:
      lnmp_dockenv:
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

networks:
  lnmp_dockenv:
    external: true
