services:
  mongo:
    image: ${DOCKER_REGISTRY}/mongo:latest
    hostname: mongo
    container_name: mongo
    restart: always
    expose:
      - 27017
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ../data/mongo:/data/db
      - ../conf/mongo:/data/configdb
      - ../logs/mongo:/var/log/mongo
    environment:
      TZ: ${TIMEZONE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    # command: mongod --config /etc/mongod.conf
    networks:
      dockenv:
        ipv4_address: ${IP_MONGO}
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

networks:
  dockenv_dockenv:
    external: true
