services:
  php56:
    image: ${DOCKER_REGISTRY}/php:56
    hostname: php56
    container_name: php56
    restart: always
    expose:
      - 9000
    ports:
      - ${PHP56_PORT}:9000
    volumes:
      - ../logs/php74:/var/log/php74
      - ${WORKSPACES}:/data
    networks:
      dockenv:
        ipv4_address: ${IP_PHP56}
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

networks:
  lnmp_dockenv:
    external: true
