services:
  php74:
    image: ${DOCKER_REGISTRY}/php:74
    hostname: php74
    container_name: php74
    restart: always
    expose:
      - 9000
    ports:
      - ${PHP74_PORT}:9000
    volumes:
      - ../logs/php74:/var/log/php74
      - ${WORKSPACES}:/data
    networks:
      - dockenv
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

networks:
  lnmp_dockenv:
    external: true
