services:
  php82:
    image: ${DOCKER_REGISTRY}/php:82
    hostname: php82
    container_name: php82
    restart: always
    expose:
      - 9000
    ports:
      - ${PHP82_PORT}:9000
    volumes:
      - ../conf/php/82/php.ini:/etc/php82/php.ini
      - ../conf/php/82/php-fpm.d:/etc/php82/php-fpm.d
      - ../conf/php/82/php-fpm.conf:/etc/php82/php-fpm.conf
      - ../logs/php/82:/var/log/php82
      - ${WORKSPACES}:/data
    networks:
      dockenv:
        ipv4_address: ${IP_PHP82}
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

networks:
  lnmp_dockenv:
    external: true
