services:
  php83:
    image: ${DOCKER_REGISTRY}/php:83
    hostname: php83
    container_name: php83
    restart: always
    expose:
      - 9000
    ports:
      - ${PHP83_PORT}:9000
    volumes:
      - ../conf/php/83/php.ini:/etc/php83/php.ini
      - ../conf/php/83/php-fpm.d:/etc/php83/php-fpm.d
      - ../conf/php/83/php-fpm.conf:/etc/php83/php-fpm.conf
      - ../logs/php/83:/var/log/php83
      - ${WORKSPACES}:/data
    networks:
      dockenv:
        ipv4_address: ${IP_PHP83}
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

networks:
  lnmp_dockenv:
    external: true
