services:
  php84:
    image: ${DOCKER_REGISTRY}/php:84
    hostname: php84
    container_name: php84
    restart: always
    expose:
      - 9000
    ports:
      - ${PHP84_PORT}:9000
    volumes:
      - ../conf/php/84/php.ini:/etc/php84/php.ini
      - ../conf/php/84/php-fpm.d:/etc/php84/php-fpm.d
      - ../conf/php/84/php-fpm.conf:/etc/php84/php-fpm.conf
      - ../logs/php/84:/var/log/php84
      - ${WORKSPACES}:/data
    # links:
      # - redis:redis
    networks:
      - lnmp_dockenv
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

networks:
  lnmp_dockenv:
    external: true
