services:
  php81:
    image: ${DOCKER_REGISTRY}/php:81
    hostname: php81
    container_name: php81
    restart: always
    expose:
      - 9000
    ports:
      - ${PHP81_PORT}:9000
    volumes:
      - ../conf/php/81/php.ini:/etc/php81/php.ini
      - ../conf/php/81/php-fpm.d:/etc/php81/php-fpm.d
      - ../conf/php/81/php-fpm.conf:/etc/php81/php-fpm.conf
      - ../logs/php/81:/var/log/php81
      - ${WORKSPACES}:/data
    networks:
      dockenv:
        ipv4_address: ${IP_PHP81}
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

networks:
  lnmp_dockenv:
    external: true
