services:
  postgres:
    image: ${DOCKER_REGISTRY}/postgres:16
    hostname: postgres
    container_name: postgres
    restart: always
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      dockenv:
        ipv4_address: ${IP_POSTGRES}
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

networks:
  lnmp_dockenv:
    external: true
