services:
  minio:
    image: ${DOCKER_REGISTRY}/valkey:latest
    hostname: valkey
    container_name: valkey
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
    command: valkey-server /usr/local/etc/valkey/valkey.conf --save 60 1 --loglevel warning
    volumes:
      - ../conf/nginx/conf.d:/usr/local/etc/valkey/valkey.conf
    networks:
      dockenv_dockenv:
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

networks:
  dockenv_dockenv:
    external: true
