services:
  # RustFS Object Storage Service(Compatible With Amazon S3 Protocol)
  rustfs:
    image: ${DOCKER_REGISTRY}/rustfs:latest
    hostname: rustfs
    container_name: rustfs
    restart: always
    environment:
      - TZ=${TIMEZONE}
      # - RUSTFS_VOLUMES=/data/rustfs{0...3} # Define 4 storage volumes
      - RUSTFS_VOLUMES=/data
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_EXTERNAL_ADDRESS=:9000 # Same as internal since no port mapping
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_ACCESS_KEY=${RUSTFS_USER}
      - RUSTFS_SECRET_KEY=${RUSTFS_PASSWORD}
      - RUSTFS_OBS_LOGGER_LEVEL=info
      - RUSTFS_OBS_ENDPOINT=${RUSTFS_OBS_ENDPOINT}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
    expose:
      - 9000
      - 9001
    ports:
      - ${RUSTFS_API_PORT}:9000 # S3 API port
      - ${RUSTFS_WEB_PORT}:9001 # Console port
    volumes:
      - ../conf/rustfs/config.yaml:/etc/rustfs/config.toml
      - ../data/rustfs:/data
      - ../logs/rustfs:/logs
    networks:
      default:
        ipv4_address: ${IP_RUSTFS}

networks:
  default:
    name: dockenv
    external: true
