version: "3.2"
services:
  # filebeat
  filebeat:
    container_name: filebeat
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:7.4.2
    restart: always
    volumes:
      - ./filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/var/log
      - /www/docker/log:/var/laravellog
      - ./filebeat/logs:/usr/share/filebeat/logs
      - ./filebeat/data:/usr/share/filebeat/data
    # 将指定容器连接到当前连接，可以设置别名，避免ip方式导致的容器重启动态改变的无法连接情况
    environment:
      - TIMEZONE=Asia/ShangHai
    links:
      - logstash
    # 依赖服务[可无]
    depends_on:
      - es-master
      - es-slave1
      - es-slave2
    networks:
      - elknet

  # es-head
  es-head:
    container_name: es-head
    image: mobz/elasticsearch-head:5
    restart: always
    ports:
      - 9100:9100
    depends_on:
      - es-master
      - es-slave1
      - es-slave2
    networks:
      - elknet

  # es监控工具
  cerebro:
    container_name: cerebro
    image: lmenezes/cerebro
    restart: always
    ports:
      - 9001:9000
    command:
      - -Dhosts.0.host=http://es-master:9200
    networks:
      - elknet

  # es索引管理
  #curator:
  #  container_name: curator
  #  image: elastic/curator
  #  environment:
  #    ELASTICSEARCH_HOST: http://es-master:9200
  #    CRON: "30 0 * * *" # 每天 0 点 30 分清理 ${UNIT_COUNT} 天之前的索引
  #    CONFIG_FILE: /usr/share/curator/config/curator.yml
  #    COMMAND: /usr/share/curator/config/delete_log_files_curator.yml
  #    UNIT_COUNT: 10
  #  network_mode: "host"
  #  restart: always
  #  depends_on:
  #    - es-master
  #    - es-slave1
  #    - es-slave2

networks:
  elknet:
    driver: bridge