services:
  nginx:
    image: ${DOCKER_REGISTRY}/nginx:latest
    container_name: nginx
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    # volumes:
    # - ./runtime/logs/nginx:/var/log/nginx
    # - ./runtime/conf/nginx:/etc/nginx
    # - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      # set php74 alias or direct to use mysql57 no alias set
      - php74:php74
      - php82:php82
    networks:
      dockenv:
        ipv4_address: ${IP_NGINX}
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

  php82:
    image: ${DOCKER_REGISTRY}/php:82
    container_name: php82
    restart: always
    depends_on:
      - mysql57
    ports:
      - "49000:9000"
    volumes:
      - ./runtime/logs/php82/:/var/log/php-fpm/
    networks:
      - dockenv
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}
