services:
  elastic:
    image: ${DOCKER_REGISTRY}/elastic:latest
    hostname: elastic
    container_name: elastic
    restart: always
    expose:
      - 9300
    environment:
      - ELASTIC_PASSWORD=dockenv
      # 此配置会导致无法启动
      # - ENROLLMENT_TOKEN=dockenv
      - cluster.name=${NAME}
      - discovery.type=single-node
      # 默认禁用 elasticsearch https 和登陆账号密码 仅适用于 Docker 测试环境
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - script.painless.regex.enabled=true
      # - node.master=false
      # - node.data=true
      - TZ=${TIMEZONE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      # - elastic:/usr/share/elasticsearch/data
      - ../data/elastic:/data
      # - ${ELASTICSEARCH_CONF_FILE}:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "${ELASTIC_WEB_PORT}:9200"
      - "${ELASTIC_PORT}:9300"
    networks:
      dockenv:
        ipv4_address: ${IP_ELASTICSEARCH}
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

  # volumes /usr/share/logstash/config/
  logstash:
    image: ${DOCKER_REGISTRY}/logstash:latest
    hostname: logstash
    container_name: logstash
    restart: always
    expose:
      - 5044
    environment:
      - TZ=${TIMEZONE}
      - ELASTICSEARCH_HOSTS=["http://elastic:9200"]
    ports:
      - "${LOGSTASH_WEB_PORT}:9600"
      - "${LOGSTASH_PORT}:5044"
    depends_on:
      - elastic
    links:
      - elastic:elasticsearch
    networks:
      dockenv:
        ipv4_address: ${IP_LOGSTASH}
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

  kibana:
    image: ${DOCKER_REGISTRY}/kibana:latest
    hostname: kibana
    container_name: kibana
    restart: always
    expose:
      - 5601
    environment:
      - TZ=${TIMEZONE}
      - SERVER_NAME=kibana
      # - ELASTICSEARCH_HOSTS=["http://${ELASTICSEARCH_IP}:9200"]
      - ELASTICSEARCH_HOSTS=["http://elastic:9200"]
      - LS_JAVA_OPTS=-Xmx512m -Xms512m
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on:
      - elastic
    links:
      - elastic:elastic
    networks:
      dockenv:
        ipv4_address: ${IP_KIBANA}
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

networks:
  dockenv:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET_IP}
          ip_range: ${DOCKER_SUBNET_RANGE}
          gateway: ${DOCKER_SUBNET_GATEWAY}