services:
  portainer:
    image: portainer/portainer-ee:latest
    hostname: portainer
    container_name: portainer
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ../data/portainer:/data
    networks:
      dockenv:
    dns:
      - ${DOCKER_DNS1}
      - ${DOCKER_DNS2}

networks:
  dockenv:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24
          ip_range: 10.10.1.0/24
          gateway: 10.10.1.254